### ISSUE TITLE
Allow the existing user to log in

### ISSUE THREAD

**Issue by kumikoono** [docomoinnovations/drupalextension#10]
When the existing user attempts to log in,  it fails as the user is not found.
```
   Given I am logged in as "BDD_user_test" # Drupal\DrupalExtension\Context\DrupalContext::assertLoggedInByName()
      No user with BDD_user_test name is registered with the driver. (InvalidArgumentException)
```
 
Ref:
https://www.drupal.org/project/drupalextension/issues/1846828

**Comment by naoi** [comment]
@kumikoono The patch has been merged, so closing this issue.
