### ISSUE TITLE
Support the transient status of a table row

### ISSUE THREAD

**Issue by kumikoono** [docomoinnovations/drupalextension#14]
When a resource is being deleted, the following three options happen:
1. the resource row show at a table with the "deleting" status
2. the resource row does not show a table
3. no table if no other resources exist

We need to support this transient status to avoid adjusting the wait time to check the page.
We also need to check multiple rows with the same text in a table.

**Comment by naoi** [comment]
@kumikoono The patch has been merged, so closing this issue.
